# SPDX-FileCopyrightText: 2026 Ján Letko <activity@ltk.solutions>
# SPDX-License-Identifier: EUPL-1.2
blank_issues_enabled: false
contact_links:
  - name: Otázka alebo diskusia
    url: https://github.com/ltksolutions/activity/discussions
    about: Pre otázky a diskusie použij GitHub Discussions, nie issues.
